swagger: "2.0"
info:
  version: 1.0.0
  title: Service Debugger API
  description: Debugger for Remote instances of Scrapper
  termsOfService: http://swagger.io/terms/
  contact:
    name: Suraj Shrestha
    email: surshrestha@growbydata.com
    url: http://apollo17march.github.io/
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: localhost:8002
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /machines:
    get:
      summary: All Machines
      description: |
        Returns a list of machine objects
      tags:
        - Machines
      responses:
        200:
          description: A list of machines
          schema:
            type: array
            items:
              $ref: '#/definitions/Machine'

  /machines/{machine_ip}:
    get:
      summary: Specific Machine
      description: |
        Returns a specified Machine Object
      tags:
        - Machines
      parameters:
        - name: machine_ip
          in: path
          description: ip address of the required machine.
          required: true
          type: number
          format: ipaddress
      responses:
        200:
          description: A list of services of specified machine
          schema:
            type: array
            items:
              $ref: '#/definitions/Machine'

  /machines/{machine_ip}/services:
    get:
      summary: All Services
      description:
        Returns all services objects for specified machine
      tags:
        - Services
      parameters:
        - name: machine_ip
          in: path
          description: ip address of the required machine.
          required: true
          type: number
          format: ipaddress
      responses:
        200:
          description: A object of specified machine
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'

  /machines/{machine_ip}/services/{service_name}:
    get:
      summary: Specific Service
      description: |
        Returns specified service object for specified machine
      tags:
        - Services
      parameters:
        - name: machine_ip
          in: path
          description: ip address of the required machine.
          required: true
          type: number
          format: ipaddress
        - name: service_name
          in: path
          description: name of the service
          required: true
          type: string
      responses:
        200:
          description: A object of specified service for specified machine
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
  /machines/{machine_ip}/services/{service_name}/progress:
    get:
      summary: Progress
      description: |
        Returns progress for specified service object of specified machine
      tags:
        - Services
      parameters:
        - name: machine_ip
          in: path
          description: ip address of the required machine.
          required: true
          type: number
          format: ipaddress
        - name: service_name
          in: path
          description: name of the service
          required: true
          type: string
      responses:
        200:
          description: A object of progress of specified service for specified machine
          schema:
            type: array
            items:
              $ref: '#/definitions/Progress'
  /machines/{machine_ip}/services/{service_name}/logs:
    get:
      summary: Log
      description: |
        Returns logs for specified service object of specified machine
      tags:
        - Services
      parameters:
        - name: machine_ip
          in: path
          description: ip address of the required machine.
          required: true
          type: number
          format: ipaddress
        - name: service_name
          in: path
          description: name of the service
          required: true
          type: string
      responses:
        200:
          description: A object of log of specified service for specified machine
          schema:
            type: array
            items:
              $ref: '#/definitions/Log'


definitions:
  Machine:
    type: object
    properties:
      model:
        type: string
        description: Model on which the current object is created
      name:
        type: string
        description: Name of the machine.
      memoryUse:
        type: string
        description: Memory use of the machine in percentage at current time.
      cpuUse:
        type: string
        description: CPU use of the machine in percentage at current time.
      project:
        type: string
        description: Project group in which the machine belongs.
      serviceCount:
        type: string
        description: Number of services currently running in the system for our specified task
      ipAddress:
        type: string
        description: IP address of the machine
      services:
        type: object
        description: Service object
  Service:
    type: object
    properties:
      model:
        type: string
        description: Model on which the current object is created
      host:
        type: string
        description: Host on which the current service is running.
      port:
        type: string
        description: Port on which the current service is running.\
      name:
        type: string
        description: Name of the service
      status:
        type: string
        description: Status of the service(up/down)
      upTime:
        type: string
        description: Uptime of the service
      machine:
        type: string
        description: identifier for the machine where the service is residing
      log:
        type: object
        description: Log object
      progress:
        type: object
        description: Progress object
  Log:
    type: object
    properties:
      model:
        type: string
        description: Model on which the current object is created
      description:
        type: string
        description: some description of the log
      service:
        type: string
        description: Identifier for the service
      logLocation:
        type: string
        description: loglocation of the service
      machine:
        type: string
        description: Identifier for the machine
  Progress:
    type: object
    properties:
      model:
        type: string
        description: Model on which the current object is created
      service:
        type: string
        description: Identifier for the service
      size:
        type: string
        description: Size of the output generated at tyhe current time
      percentage:
        type: string
        description: output by percentage
      machine:
        type: string
        description: Identifier for the machine